version: '3'
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules # don't try to link the node_modules in the container with sth from outside of it
            - .:/app # map the current directory into the /app directory inside the container
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]